# Generated by Django 4.2.5 on 2023-11-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tipo_cliente', models.CharField(choices=[('individual', 'Individual'), ('empresa', 'Empresa')], max_length=20)),
                ('empresa', models.CharField(max_length=50, null=True, verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('legajo', models.IntegerField(verbose_name='Legajo')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_fc', models.CharField(verbose_name='Remito/FC')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(unique=True, verbose_name='SKU')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=10, verbose_name='Ubicación')),
                ('estado', models.CharField(default='vacia', max_length=8, verbose_name='Estado de la posición')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingresos')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posiciones')),
            ],
        ),
        migrations.AddField(
            model_name='ingresos',
            name='materiales',
            field=models.ManyToManyField(through='core.Stock', to='core.material'),
        ),
        migrations.CreateModel(
            name='EmpleadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
