# Generated by Django 4.2.5 on 2023-11-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stock_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_OC', models.CharField(verbose_name='Remito / OC')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('cantidad', models.PositiveBigIntegerField(verbose_name='Cantidad')),
                ('pedido_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
    ]
