# Generated by Django 4.2.5 on 2023-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_empleado_empleadocliente_materiales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clientes',
            field=models.ManyToManyField(null=True, through='core.EmpleadoCliente', to='core.cliente'),
        ),
    ]
