# Generated by Django 4.2.5 on 2023-11-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='pedido_stock',
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('del_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedidos')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido_stock',
            field=models.ManyToManyField(through='core.Salidas', to='core.material'),
        ),
    ]
