# Generated by Django 4.2.5 on 2023-10-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_empleado_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clientes',
            field=models.ManyToManyField(default=9999, through='core.EmpleadoCliente', to='core.cliente'),
        ),
    ]
